"""initial schema

Revision ID: e41603ce228e
Revises: 
Create Date: 2026-03-17 19:26:42.002027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e41603ce228e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('workflow',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('user', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.Column('slurm_defaults', sa.Text(), nullable=True),
    sa.Column('resource_monitor_config', sa.Text(), nullable=True),
    sa.Column('execution_config', sa.Text(), nullable=True),
    sa.Column('use_pending_failed', sa.Integer(), nullable=False),
    sa.Column('project', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('access_group_member',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['access_group.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'username')
    )
    op.create_table('compute_node',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.Text(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('num_cpus', sa.Integer(), nullable=True),
    sa.Column('memory_gb', sa.Float(), nullable=True),
    sa.Column('num_gpus', sa.Integer(), nullable=True),
    sa.Column('num_nodes', sa.Integer(), nullable=True),
    sa.Column('time_limit', sa.Float(), nullable=True),
    sa.Column('scheduler_config_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_compute_node_workflow_id', 'compute_node', ['workflow_id'], unique=False)
    op.create_table('event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_event_workflow_id', 'event', ['workflow_id'], unique=False)
    op.create_table('failure_handler',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('rules', sa.Text(), nullable=True),
    sa.Column('default_max_retries', sa.Integer(), nullable=False),
    sa.Column('default_recovery_command', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_failure_handler_workflow_id', 'failure_handler', ['workflow_id'], unique=False)
    op.create_table('file',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('st_mtime', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_file_workflow_id', 'file', ['workflow_id'], unique=False)
    op.create_table('local_scheduler',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('num_cpus', sa.Integer(), nullable=True),
    sa.Column('memory', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource_requirements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('num_cpus', sa.Integer(), nullable=True),
    sa.Column('num_gpus', sa.Integer(), nullable=True),
    sa.Column('num_nodes', sa.Integer(), nullable=True),
    sa.Column('memory', sa.Text(), nullable=True),
    sa.Column('runtime', sa.Text(), nullable=True),
    sa.Column('memory_bytes', sa.Integer(), nullable=True),
    sa.Column('runtime_s', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rr_workflow_id', 'resource_requirements', ['workflow_id'], unique=False)
    op.create_table('slurm_scheduler',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('account', sa.Text(), nullable=True),
    sa.Column('partition', sa.Text(), nullable=True),
    sa.Column('slurm_config', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('is_ephemeral', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_data_workflow_id', 'user_data', ['workflow_id'], unique=False)
    op.create_table('workflow_access_group',
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['access_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workflow_id', 'group_id')
    )
    op.create_table('workflow_action',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('trigger_type', sa.Text(), nullable=False),
    sa.Column('action_type', sa.Text(), nullable=False),
    sa.Column('job_ids', sa.Text(), nullable=True),
    sa.Column('job_name_regex', sa.Text(), nullable=True),
    sa.Column('commands', sa.Text(), nullable=True),
    sa.Column('trigger_count', sa.Integer(), nullable=False),
    sa.Column('required_triggers', sa.Integer(), nullable=False),
    sa.Column('executed', sa.Integer(), nullable=False),
    sa.Column('executed_at', sa.Float(), nullable=True),
    sa.Column('persistent', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workflow_action_workflow_id', 'workflow_action', ['workflow_id'], unique=False)
    op.create_table('workflow_status',
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Integer(), nullable=False),
    sa.Column('is_canceled', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workflow_id')
    )
    op.create_table('job',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('command', sa.Text(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('resource_requirements_id', sa.Integer(), nullable=True),
    sa.Column('scheduler_id', sa.Integer(), nullable=True),
    sa.Column('failure_handler_id', sa.Integer(), nullable=True),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('unblocking_processed', sa.Integer(), nullable=False),
    sa.Column('cancel_on_blocking_job_failure', sa.Integer(), nullable=False),
    sa.Column('supports_termination', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['failure_handler_id'], ['failure_handler.id'], ),
    sa.ForeignKeyConstraint(['resource_requirements_id'], ['resource_requirements.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_job_status', 'job', ['status'], unique=False)
    op.create_index('idx_job_unblocking_pending', 'job', ['workflow_id', 'unblocking_processed'], unique=False, sqlite_where=sa.text('status IN (5,6,7,8) AND unblocking_processed=0'))
    op.create_index('idx_job_workflow_id', 'job', ['workflow_id'], unique=False)
    op.create_index('idx_job_workflow_status', 'job', ['workflow_id', 'status'], unique=False)
    op.create_index('idx_job_workflow_status_priority', 'job', ['workflow_id', 'status', 'priority'], unique=False)
    op.create_table('job_depends_on',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('depends_on_job_id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_job_id'], ['job.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id', 'depends_on_job_id')
    )
    op.create_index('idx_job_depends_on_depends_on_job_id', 'job_depends_on', ['depends_on_job_id'], unique=False)
    op.create_index('idx_job_depends_on_workflow', 'job_depends_on', ['workflow_id'], unique=False)
    op.create_table('job_input_file',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id', 'file_id')
    )
    op.create_table('job_input_user_data',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('user_data_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_data_id'], ['user_data.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id', 'user_data_id')
    )
    op.create_table('job_internal',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('input_hash', sa.Text(), nullable=True),
    sa.Column('active_compute_node_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('job_output_file',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id', 'file_id')
    )
    op.create_table('job_output_user_data',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('user_data_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_data_id'], ['user_data.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id', 'user_data_id')
    )
    op.create_table('result',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('compute_node_id', sa.Integer(), nullable=True),
    sa.Column('return_code', sa.Integer(), nullable=True),
    sa.Column('exec_time_minutes', sa.Float(), nullable=True),
    sa.Column('completion_time', sa.Float(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('peak_memory_bytes', sa.Integer(), nullable=True),
    sa.Column('avg_memory_bytes', sa.Integer(), nullable=True),
    sa.Column('peak_cpu_percent', sa.Float(), nullable=True),
    sa.Column('avg_cpu_percent', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['compute_node_id'], ['compute_node.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'run_id')
    )
    op.create_index('idx_result_workflow_job', 'result', ['workflow_id', 'job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_result_workflow_job', table_name='result')
    op.drop_table('result')
    op.drop_table('job_output_user_data')
    op.drop_table('job_output_file')
    op.drop_table('job_internal')
    op.drop_table('job_input_user_data')
    op.drop_table('job_input_file')
    op.drop_index('idx_job_depends_on_workflow', table_name='job_depends_on')
    op.drop_index('idx_job_depends_on_depends_on_job_id', table_name='job_depends_on')
    op.drop_table('job_depends_on')
    op.drop_index('idx_job_workflow_status_priority', table_name='job')
    op.drop_index('idx_job_workflow_status', table_name='job')
    op.drop_index('idx_job_workflow_id', table_name='job')
    op.drop_index('idx_job_unblocking_pending', table_name='job', sqlite_where=sa.text('status IN (5,6,7,8) AND unblocking_processed=0'))
    op.drop_index('idx_job_status', table_name='job')
    op.drop_table('job')
    op.drop_table('workflow_status')
    op.drop_index('idx_workflow_action_workflow_id', table_name='workflow_action')
    op.drop_table('workflow_action')
    op.drop_table('workflow_access_group')
    op.drop_index('idx_user_data_workflow_id', table_name='user_data')
    op.drop_table('user_data')
    op.drop_table('slurm_scheduler')
    op.drop_index('idx_rr_workflow_id', table_name='resource_requirements')
    op.drop_table('resource_requirements')
    op.drop_table('local_scheduler')
    op.drop_index('idx_file_workflow_id', table_name='file')
    op.drop_table('file')
    op.drop_index('idx_failure_handler_workflow_id', table_name='failure_handler')
    op.drop_table('failure_handler')
    op.drop_index('idx_event_workflow_id', table_name='event')
    op.drop_table('event')
    op.drop_index('idx_compute_node_workflow_id', table_name='compute_node')
    op.drop_table('compute_node')
    op.drop_table('access_group_member')
    op.drop_table('workflow')
    op.drop_table('access_group')
    # ### end Alembic commands ###
